# SPDX-License-Identifier: GPL-2.0
#
# Makefile for kernel SPI drivers.
#

# ccflags-$(CONFIG_STM32ECU_DEBUG) := -DDEBUG
ccflags-m := -DDEBUG

# small core, mostly translating board-specific
# config declarations into driver model code
# obj-$(CONFIG_STM32ECU)		+= stm32ecu.o
obj-m		+= stm32ecu.o
