#ifndef ASSITYPES_H
#define ASSITYPES_H

typedef enum {
  ASSI_STATE_OFF,
  ASSI_STATE_YELLOW_SOLID,
  ASSI_STATE_YELLOW_FLASH,
  ASSI_STATE_BLUE_SOLID,
  ASSI_STATE_BLUE_FLASH,
  ASSI_STATE_MAX,
} ASSIState_en;

#endif // ASSITYPES_H
