
#ifndef ASSTATETYPES_H
#define ASSTATETYPES_H

typedef enum {
    AS_STATE_OFF,
    AS_STATE_READY,
    AS_STATE_DRIVING,
    AS_STATE_EMERGENCY,
    AS_STATE_FINISHED,
    AS_STATE_MAX
} AutonomousState_en;

#endif // ASSTATETYPES_H
